package com.study.mashroomsapps.entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.study.mashroomsapps.entities.Mashrooms;

import com.study.mashroomsapps.entities.MashroomsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mashroomsDaoConfig;

    private final MashroomsDao mashroomsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mashroomsDaoConfig = daoConfigMap.get(MashroomsDao.class).clone();
        mashroomsDaoConfig.initIdentityScope(type);

        mashroomsDao = new MashroomsDao(mashroomsDaoConfig, this);

        registerDao(Mashrooms.class, mashroomsDao);
    }
    
    public void clear() {
        mashroomsDaoConfig.clearIdentityScope();
    }

    public MashroomsDao getMashroomsDao() {
        return mashroomsDao;
    }

}
